refactor install and init scripts to automate to match the new config format

diff --git a/installer-files/bin/install b/installer-files/bin/install
--- a/installer-files/bin/install
+++ b/installer-files/bin/install
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 
-# needed in order to read the config
-apk add yq
+config_path="./config"
+
 
 config() {
 	cat /root/config/choices.yml | yq eval .$1 -
@@ -21,6 +21,26 @@ persist() {
 	# saves filesystem changes to persist after install and reboot
 	lbu add $1
 }
+
+verbose=$(config 'verbose')
+
+
+#===============
+# dependency checks
+#===============
+
+
+if [ $(config 'graphics.preset') = "river" ] && ! enabled 'system.repository.apk.test'
+then
+	echo "error: riverwm requires enabling the apk test repository (system.repository.apk.test in choices.yml)"
+	exit 1
+fi
+
+
+#===============
+# alpine install
+#===============
+
 
 # keyboard
 layout=$(config 'system.keyboard.layout')
@@ -61,6 +81,7 @@ then
 	args="-c $args"
 fi
 setup-apkrepos $args
+# TODO: test
 if enabled 'system.repository.apk.edge-testing'
 then
 	mirror_url=$(cat /etc/apk/repositories | tail -n 1 | cut -d "/" -f 1-4)
@@ -72,9 +93,10 @@ fi
 # main user
 username=$(config 'system.user.username')
 password=$(config 'system.user.password')
+fullname=$(config 'system.user.fullname')
 # -a: admin (using this installs doas automatically)
 # -g: groups
-setup-user -a -g 'audio video netdev' "$username"
+setup-user -a -g 'audio video netdev' -f "$fullname" "$username"
 # TODO: adduser $username plugdev (if enabled 'system.services.networkmanager')
 # the 'plugdev' group is added by NetworkManager, for rootless network management
 
@@ -86,11 +108,13 @@ cp /root/setup /home/"$username"
 persist /home/$username
 
 
+# boot system services
 if enabled "system.services.seedrng"
 then
 	rc-update add seedrng boot
 fi
 
+# other system services
 for service in crond acpid
 do
 	if enabled "system.services.$service"
@@ -100,28 +124,11 @@ do
 done
 
 
+#==========================
+# Custom configuration
+#==========================
 
-# disk install
-yes | setup-disk -m sys /dev/vda
-
-#!/bin/sh
-
-# assumes alpine linux is already installed, and the script is running from an existing fresh install
-
-
-# setup config:
-config() {
-	cat config/choices.yml | yq eval .$1 -
-}
-
-enabled() {
-	if [ "$(config "$1")" = true ]
-	then
-		return 0
-	else
-		return 1
-	fi
-}
+# TODO:
 
 pkgadd() {
 	pkg="$1"
@@ -133,15 +140,27 @@ pkgadd() {
 	fi
 }
 
-error() {
-	msg="$1"
-	src="$2"
+pkgdel() {
+	pkg="$1"
+	if $verbose
+	then
+		apk del $pkg
+	else
+		apk del $pkg > /dev/null
+	fi
 }
 
-# do not test for real without a virtual environment
-exit 0
+error() {
+	src="$1"
+	msg="$2"
+	echo "error: $msg ($src)"
+}
 
-verbose=$(config 'verbose')
+error_unknown() {
+	setting="$1"
+	error $setting "unrecognized_setting"
+}
+
 
 # lock root account
 passwd -l root
@@ -150,7 +169,7 @@ passwd -l root
 apk update
 
 # packages
-for pkg in vim nano firefox btop
+for pkg in firefox btop
 do
 	if enabled 'packages.'$pkg
 	then
@@ -158,10 +177,15 @@ do
 		pkgadd $pkg
 	fi
 done
-if ! enabled 'packages.yq'
-then
-	apk del yq
-fi
+
+# these packages were added in the live environment
+for tmp_pkg in vim nano yq
+do
+	if ! enabled 'packages.'$tmp_pkg
+	then
+		apk del $tmp_pkg
+	fi
+done
 
 # services
 for service in polkit networkmanager udisks
@@ -175,6 +199,25 @@ do
 	fi
 done
 
+if enabled 'services.polkit'
+then
+	# TODO: test
+	#mkdir -p /etc/polkit/rules.d
+	cp "$config_path"/etc/polkit-1/rules.d/* /etc/polkit-1/rules.d/
+fi
+
+# these services were added in the live environment
+for tmp_service in networkmanager
+do
+	if ! enabled 'services.'$service
+	then
+		rc-update del $service
+		rc-service $service stop
+		apk del $service
+	fi
+done
+
+
 ssh=$(config 'services.ssh')
 case $ssh in
 	openssh)
@@ -184,7 +227,7 @@ case $ssh in
 		echo "skipping ssh server"
 		;;
 	*)
-		error "unrecognized setting" "services.ssh"
+		error_unknown "services.ssh"
 esac
 
 
@@ -192,96 +235,117 @@ esac
 preset=$(config 'graphics.preset')
 case $preset in
 	river)
-		if ! enabled 'system.repository.apk.test'
-		then
-			echo "warning: riverwm requires enabling the apk test repository (system.repository.apk.test in choices.yml)"
-		fi
-		launchbar=$(config 'graphics.options.river.launcher')
+		echo "setting up river window manager"
+
+		pkgadd river
+		rc-service seatd start
+		rc-update add seatd
+		adduser $(config '.system.user') seat
+		pkgadd xwayland
+
+		# udev is already setup by the init script
+		#setup-devd udev
+
+		# configure river
+		path="/home/$username/.config/river"
+		mkdir -p "$path"
+
+		cp "$config_path"/river/river-init "$path/init"
+		chmod +x "$path/init"
+
+
+
+		launcher=$(config 'graphics.options.river.launcher')
+		case $launcher in
+			bemenu)
+				pkgadd bemenu
+				;;
+			wofi)
+				error "not implemented" graphics.options.river.launcher
+				;;
+			none)
+				;;
+			*)
+				error_unknown graphics.options.river.launcher
+		apk add bemenu
+
 		bar=$(config 'graphics.options.river.bar')
+		case $bar in
+			waybar)
+				mkdir "/home/$username/.config/waybar"
+				cp "$config_path"/river/waybar-config.json "$path"/.config/waybar/config
+				pkgadd waybar
+				;;
+			none)
+				;;
+			*)
+				error_unknown graphics.options.river.bar
+		esac
+
+		cp configs/river/xdg-profile.sh /etc/profile.d/xdg-runtime-dir.sh
+		# TODO: chmod +x ?
+
+		pkgadd font-dejavu
+
 		background=$(config 'graphics.options.river.background')
-		login=$(config 'graphics.options.river.login')
+		case $background in
+			swaybg)
+				pkgadd swaybg
+				;;
+			none)
+				;;
+			*)
+				error_unknown graphics.options.river.background
+		esac
 		terminal=$(config 'graphics.options.river.terminal')
+		case $terminal in
+			foot)
+				pkgadd foot
+				;;
+			*)
+				error_unknown graphics.options.river.terminal
+		esac
+
+		pkgadd dbus dbus-x11 # needed for waybar
+
+		explorer=$(config 'graphics.options.river.explorer')
+		case $explorer in
+			thunar)
+				pkgadd thunar
+				;;
+			none)
+				;;
+			*)
+				error_unknown graphics.options.river.explorer
+				;;
+		esac
+		login=$(config 'graphics.options.river.login')
+		case $login in
+			greetd-wlgreet)
+				echo "setting up greetd session manager"
+				pkgadd greetd-wlgreet
+				cp "$config_path"/river/greetd-config.toml /etc/greetd/config.toml
+				cp configs/river/river-wlgreet-config /etc/greetd/river-wlgreet-config
+
+				adduser greetd seat
+				# TODO: carefully test before doing this
+				# (every failed test interrupts the terminal)
+				#rc-service greetd start
+				#rc-update add greetd
+				;;
+			none)
+				;;
+			*)
+				;;
+		esac
 		echo "not implemented"
-		echo "launchbar: $launchbar"
-		echo "bar: $bar"
-		echo "background: $background"
 		echo "login: $login"
-		echo "terminal: $terminal"
 		;;
 	xfce)
 		echo "not implemented"
 		;;
 esac
 
-gui=$(config '.wm-presets.[0].name')
-# case/esac
-if [ "$gui" = "river" ]
-then
-	echo "setting up river window manager"
-	# add edge testing repos
-	# TODO: fix the content of repository-config
-	# TODO: refactor configs into a file
-	cat configs/river/apk-edge-repository >> /etc/apk/repositories
-	apk add river
-	rc-service seatd start
-	rc-update add seatd
-	adduser $(config '.system.user') seat
-	apk add xwayland
-	setup-devd udev
-	# TODO: make this path-independant
-	# (/home/{system user}/.config/river/init)
-	path=".config/river"
-	mkdir -p .config/river
-	#touch .config/river/init
-	#chmod +x .config/river/init
-	cp configs/river/river-init .config/river/init
-	chmod +x .config/river/init
-
-	mkdir .config/waybar
-	cp configs/river/waybar-config.json .config/waybar/config
-
-	cp configs/river/xdg-profile.sh /etc/profile.d/xdg-runtime-dir.sh
-	# TODO: chmod +x ?
-
-	apk add font-dejavu
-
-	# utilities
-	apk add swaybg
-	apk add firefox
-	apk add foot
-	apk add waybar
-	apk add dbus dbus-x11 # needed for waybar
-	launchbar=$(config '.wm-presets.[0].options.launchbar.[0]')
-	# TODO: implement wofi choice
-	if [ "$launchbar" = "bemenu" ]
-	then
-		apk add bemenu
-	fi
-	apk add thunar
-
-
-
-	# session management
-	login=$(config '.wm-presets.[0].options.login.[0]')
-	if [ "$login" = "greetd-wlgreet" ]
-	then
-		echo "setting up greetd session manager"
-		apk add greetd-wlgreet
-		cp configs/river/greetd-config.toml /etc/greetd/config.toml
-		cp configs/river/river-wlgreet-config /etc/greetd/river-wlgreet-config
-
-		adduser greetd seat
-		# TODO: carefully test before doing this
-		#rc-service greetd start
-		#rc-update add greetd
-	fi
-
-fi
-
-
-optionals=$(config '.optional')
-# TODO: for loop and apk add on each item
-echo "not implemented: auto-installing optional features: $optionals"
-
-
+# disk install
+yes | setup-disk -m sys /dev/vda
 
